Feat: enabling email notifications for failed dags
bcgov/cas-airflow pull request #67
Opened 2021-04-15 23:51 UTC by pbastia

This PR is to enable email notifications for failed DAGs

2021-04-20 22:24 UTC, matthieu-foucault requested changes
Looks good, just some minor changes needed

2021-04-20 22:24 UTC, matthieu-foucault commented on dags/automated_email_test_dag.py
> +"""
The DAG description needs an update

2021-04-20 22:24 UTC, matthieu-foucault commented on helm/cas-airflow/templates/cronJobs/test-email-on-failure-cronjob.yaml
> +      ttlSecondsAfterFinished: 10
Did we establish if this is supported by OCP4?

2021-04-20 22:24 UTC, matthieu-foucault commented on helm/cas-airflow/templates/cronJobs/test-email-on-failure-cronjob.yaml
> +                - echo "This CronJob purposely fails, airflow should report an error to ggircs@gov.bc.ca" && exit 1
add newline at end of file

2021-04-21 15:16 UTC, matthieu-foucault approved these changes

2021-04-21 15:16 UTC, pbastia commented on dags/automated_email_test_dag.py
> +"""
oops

2021-04-21 15:19 UTC, merged